# Generated by Django 4.2.17 on 2025-04-15 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
        migrations.AddField(
            model_name='attendance',
            name='logout_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_working_hours',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
