# Generated by Django 4.2.17 on 2025-06-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20250415_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyDetails',
            fields=[
            ],
            options={
                'verbose_name': 'Monthly Detail',
                'verbose_name_plural': 'Monthly Details',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('employee.employee',),
        ),
        migrations.RemoveField(
            model_name='salarydisbursement',
            name='unpaid_reason',
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(default='Present', max_length=20),
        ),
        migrations.AlterField(
            model_name='salarydisbursement',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='June', max_length=20),
        ),
        migrations.AlterField(
            model_name='salarydisbursement',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Hold', 'Hold')], default='Unpaid', max_length=10),
        ),
    ]
