# services:
#   - type: web
#     name: employee-management
#     env: python
#     buildCommand: pip install -r requirements.txt
#     startCommand: bash -c "python manage.py migrate && gunicorn empmanagement.wsgi"
#     envVars:
#       - key: PYTHON_VERSION
#         value: 3.10.0
#       - key: DEBUG
#         value: "False"
#       - key: DISABLE_COLLECTSTATIC
#         value: "0"
#       - key: ALLOWED_HOSTS
#         value: "*"
#       - key: SECRET_KEY
#         generateValue: true
#       - key: WEB_CONCURRENCY
#         value: "4"
#       - key: DATABASE_URL
#         fromDatabase:
#           name: employee-management-db  # <-- use the name of your actual Render database
#           property: connectionString
#     plan: free


services:
  - type: web
    name: employee-management
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn empmanagement.wsgi
    postDeployCommand: python manage.py migrate
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DEBUG
        value: "False"
      - key: DISABLE_COLLECTSTATIC
        value: "0"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "4"
      - key: DATABASE_URL
        fromDatabase:
          name: employee-management-db
          property: connectionString
    plan: free
