services:
  - type: web
    name: employee-management
    env: python
    buildCommand: |
      pip install --upgrade pip &&
      pip install -r requirements.txt
    startCommand: |
      bash -c "
        echo 'Waiting for database to be ready...';
        until python manage.py migrate --noinput; do
          echo 'Waiting for DB...';
          sleep 5;
        done;
        echo 'Collecting static files...';
        python manage.py collectstatic --noinput;
        echo 'Starting server...';
        gunicorn --config gunicorn_config.py empmanagement.wsgi:application --bind 0.0.0.0:$PORT
      "
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DEBUG
        value: "False"
      - key: DISABLE_COLLECTSTATIC
        value: "0"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "1"  # Reduced for free tier
      - key: GUNICORN_CMD_ARGS
        value: "--workers=1 --timeout=120"
      - key: DATABASE_URL
        fromDatabase:
          name: employee-management-db
          property: connectionString
      - key: PYTHONUNBUFFERED
        value: "1"
    plan: free
    buildCommandPriority: 2
    autoDeploy: true
