services:
  - type: web
    name: employee-management
    env: python
    buildCommand: |
      pip install --upgrade pip &&
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput
    startCommand: |
      python manage.py migrate --noinput &&
      gunicorn empmanagement.wsgi:application --config gunicorn_prod.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DEBUG
        value: "False"
      - key: DISABLE_COLLECTSTATIC
        value: "1"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: employee-management-db
          property: connectionString
      - key: PYTHONUNBUFFERED
        value: "1"
    plan: free
